spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board_back
    username: jisu
    password: 1234
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: create #create update none

